# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.srcs/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/block_design_hdmi_text_controller_0_0.xci
# IP: The module: 'block_design_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/blk_mem_gen_2/blk_mem_gen_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_2 || ORIG_REF_NAME==blk_mem_gen_2} -quiet] -quiet

# IP: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/blk_mem_gen_1/blk_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc

# XDC: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: C:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.srcs/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/block_design_hdmi_text_controller_0_0.xci
# IP: The module: 'block_design_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/blk_mem_gen_2/blk_mem_gen_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_2 || ORIG_REF_NAME==blk_mem_gen_2} -quiet] -quiet

# IP: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/blk_mem_gen_1/blk_mem_gen_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/hdmi_tx_0/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc

# XDC: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_hdmi_text_controller_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc
