# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab7_1_provided_fa23_2/mb_usb_hdmi_top.xdc

# XDC: imports/Downloads/urbana_ddr3.xdc

# Block Designs: bd/block_design/block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design || ORIG_REF_NAME==block_design} -quiet] -quiet

# IP: bd/block_design/ip/block_design_microblaze_0_1/block_design_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_microblaze_0_1 || ORIG_REF_NAME==block_design_microblaze_0_1} -quiet] -quiet

# IP: bd/block_design/ip/block_design_mig_7series_0_0/block_design_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_mig_7series_0_0 || ORIG_REF_NAME==block_design_mig_7series_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_xbar_1/block_design_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_xbar_1 || ORIG_REF_NAME==block_design_xbar_1} -quiet] -quiet

# IP: bd/block_design/ip/block_design_microblaze_0_axi_periph_1/block_design_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_microblaze_0_axi_periph_1 || ORIG_REF_NAME==block_design_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/block_design/ip/block_design_microblaze_0_axi_intc_1/block_design_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_microblaze_0_axi_intc_1 || ORIG_REF_NAME==block_design_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/block_design/ip/block_design_mdm_1_1/block_design_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_mdm_1_1 || ORIG_REF_NAME==block_design_mdm_1_1} -quiet] -quiet

# IP: bd/block_design/ip/block_design_rst_mig_7series_0_83M_0/block_design_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==block_design_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_uartlite_0_1/block_design_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_axi_uartlite_0_1 || ORIG_REF_NAME==block_design_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/block_design/ip/block_design_hdmi_text_controller_0_0/block_design_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_hdmi_text_controller_0_0 || ORIG_REF_NAME==block_design_hdmi_text_controller_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_3/block_design_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_auto_pc_3 || ORIG_REF_NAME==block_design_auto_pc_3} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_0/block_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_auto_pc_0 || ORIG_REF_NAME==block_design_auto_pc_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_1/block_design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_auto_pc_1 || ORIG_REF_NAME==block_design_auto_pc_1} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_2/block_design_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_auto_pc_2 || ORIG_REF_NAME==block_design_auto_pc_2} -quiet] -quiet

# XDC: c:/Users/Alyssa/Documents/ece385/ece385/final_project/final_project.gen/sources_1/bd/block_design/block_design_ooc.xdc
