# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/shivg/Desktop/ece385/final_project/final_project.srcs/sources_1/bd/block_design/ip/block_design_rst_mig_7series_0_83M_0/block_design_rst_mig_7series_0_83M_0.xci
# IP: The module: 'block_design_rst_mig_7series_0_83M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shivg/Desktop/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_rst_mig_7series_0_83M_0/block_design_rst_mig_7series_0_83M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_rst_mig_7series_0_83M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shivg/Desktop/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_rst_mig_7series_0_83M_0/block_design_rst_mig_7series_0_83M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_rst_mig_7series_0_83M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shivg/Desktop/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_rst_mig_7series_0_83M_0/block_design_rst_mig_7series_0_83M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_rst_mig_7series_0_83M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/shivg/Desktop/ece385/final_project/final_project.srcs/sources_1/bd/block_design/ip/block_design_rst_mig_7series_0_83M_0/block_design_rst_mig_7series_0_83M_0.xci
# IP: The module: 'block_design_rst_mig_7series_0_83M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shivg/Desktop/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_rst_mig_7series_0_83M_0/block_design_rst_mig_7series_0_83M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_rst_mig_7series_0_83M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shivg/Desktop/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_rst_mig_7series_0_83M_0/block_design_rst_mig_7series_0_83M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_rst_mig_7series_0_83M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shivg/Desktop/ece385/final_project/final_project.gen/sources_1/bd/block_design/ip/block_design_rst_mig_7series_0_83M_0/block_design_rst_mig_7series_0_83M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_rst_mig_7series_0_83M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
